apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-repo-update
spec:
  description: >-
    These Tasks are Git tasks to work with repositories used by other tasks
    in your Pipeline.

    The git-repo-update Task will fetch the gitops repo and update the config file and push it back to git.
  workspaces:
  - name: source
    description: The git repo will be fetched onto the volume backing this Workspace.
  params:
  - description: Name of the argocd application
    name: argocd-app-name
    type: string
  - description: Path to the gitops values file 
    name: configFile
    type: string
  - description:  The git repository URL to clone from.
    name: configGitUrl
    type: string
  - description: The new image to be updated
    name: image-full-path-with-tag
    type: string
  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.source.path)/$(inputs.params.argocd-app-name)"
    script: |
      #!/usr/bin/env sh
      set -e

      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'

      git init
      git remote add origin $(inputs.params.configGitUrl)
      git fetch --depth 1 origin main
      git checkout main

  - name: update-yaml
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.source.path)/$(inputs.params.argocd-app-name)"
    script: |
      #!/usr/bin/env sh
      set -e

      echo "updating image to $(inputs.params.image-full-path-with-tag)"
      tag=$(echo $(inputs.params.image-full-path-with-tag) | cut -f2 -d :)
      echo "Updating to Image Tag: ${tag}"
      sed -i "s|^  tag:.*|  tag: ${tag}|" $(workspaces.source.path)/$(inputs.params.argocd-app-name)/$(inputs.params.configFile)

  - name: push-changes-to-gitops-repo
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.source.path)/$(inputs.params.argocd-app-name)"
    script: |
      #!/usr/bin/env sh
      set -e

      git config --global user.email "glaceroy@gmail.com"
      git config --global user.name "Mohsin Aiyaz Ahmad Khan"
      git add .
      git commit --allow-empty -m "[tekton] updating image to $(inputs.params.image-full-path-with-tag)"
      
      eval $(ssh-agent)
      ssh-add ~/.ssh/id_*
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push origin main

