kind: PersistentVolume
apiVersion: v1
metadata:
  name: tekton-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/tekton"
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem