apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildah-sa
  namespace: default
secrets:
  - name: docker-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipeline-deploy
rules:
- apiGroups: [""]
  resources: ["secrets", "services", "pods"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: tekton-pipeline-deploy-rb
    namespace: default
subjects:
    - kind: ServiceAccount
      name: buildah-sa
      namespace: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: tekton-pipeline-deploy