apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitops-deploy-eventlistener
spec:
  serviceAccountName: tekton-github-triggers
  triggers:
  - name: github-listener
    interceptors:
    - github:
        secretRef:
          secretName: github-trigger-secret
          secretKey: secretToken
        eventTypes:
        - push
    - cel:
        filter: "body.ref == 'refs/heads/main'"
    bindings:
    - ref: build-deploy-binding
    template:
      ref: build-push-gitops-deploy-template