apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-push-gitops-deploy-template
spec:
  params:
  - name: buildRevision
    description: The Git commit revision
  - name: buildRepo
    description: The Git repository to build image from
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-build-push-gitops-deploy-
    spec:
      serviceAccountName: buildah-sa
      pipelineRef:
        name: pipeline-build-push-gitops-deploy
      params:
      - name: repo-url
        value: $(tt.params.buildRepo)
      - name: buildRevision
        value: $(tt.params.buildRevision)
      - name: python-file
        value: main.py
      - name: image-full-path-with-tag
        value: glaceroy/smesh-dashboard:v1.4
      - name: deployment-name
        value: smesh-dashboard
      - name: deployment-namespace
        value: smesh-dashboard
      - name: argocd-app-name
        value: smesh-dashboard
      - name: configFile
        value: helm-config/values.yaml
      - name: configGitUrl
        value: https://github.com/glaceroy/smesh-dashboard
      workspaces:
      - name: workspace
        persistentvolumeclaim:
          claimName: tekton-pvc
      - name: empty-dir
        emptyDir: {}
      

