apiVersion: apps/v1
kind: Deployment
metadata:
  name: smesh-dashboard
  namespace: smesh-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: smesh-dashboard
      app.kubernetes.io/name: smesh-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: smesh-dashboard
        app.kubernetes.io/name: smesh-dashboard
    spec:
      containers:
      - image: glaceroy/smesh-dashboard:v1.3
        imagePullPolicy: IfNotPresent
        name: smesh-dashboard
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/endpoints-config
          name: endpoints-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: smesh-dashboard-sa
      serviceAccountName: smesh-dashboard-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: endpoints-config
        name: endpoints-config
