apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-build-push-gitops-deploy-
spec:
  serviceAccountName: buildah-sa
  pipelineRef:
    name: pipeline-build-push-gitops-deploy
  params:
  - name: repo-url
    value: https://github.com/glaceroy/smesh_pattern_status
  - name: buildRevision
    value: ''
  - name: python-file
    value: main.py
  - name: image-full-path-with-tag
    value: glaceroy/smesh-dashboard:v1.3
  - name: deployment-name
    value: smesh-dashboard
  - name: deployment-namespace
    value: smesh-dashboard
  - name: argocd-app-name
    value: smesh-dashboard
  - name: configFile
    value: helm-config/values.yaml
  - name: configGitUrl
    value: git@github.com:glaceroy/smesh-dashboard.git
  workspaces:
  - name: workspace
    persistentvolumeclaim:
      claimName: tekton-pvc
  - name: empty-dir
    emptyDir: {}
      

