apiVersion: v1
kind: Secret
metadata:
  name: github-trigger-secret
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/basic-auth
stringData:
  username: glaceroy
  password: Aysha8790@