apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDblptV2hYTTdxS3FxMnArQ3FKWlBTaXlVSXhNTjN1R0prdldwQkFnTmR5Z0FBQUpqdWhUSWI3b1V5Ckd3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ25abVdoWE03cUtxcTJwK0NxSlpQU2l5VUl4TU4zdUdKa3ZXcEJBZ05keWcKQUFBRUQ5ZUozaEJzbVVqMkFLUVVobVAzMkxvN3FjYUtzRlhRSWhpVE1Bclg4Z0phZG1aYUZjenVvcXFyYW40S29sazlLTApKUWpFdzNlNFltUzlha0VDQTEzS0FBQUFFbWRzWVdObGNtOTVRR2R0WVdsc0xtTnZiUUVDQXc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K